### PR TITLE
Fix data race in SSH

### LINKED ISSUE #435: SSH data race
Sometimes when executing ssh integration environment, and running ssh test a data race appears on the ssh server node. Attached are the logs for every node, the data race appears in A log, line 126.

[nodeA.log](https://github.com/skycoin/skywire/files/3325443/nodeA.log)
[nodeB.log](https://github.com/skycoin/skywire/files/3325444/nodeB.log)
[nodeC.log](https://github.com/skycoin/skywire/files/3325445/nodeC.log)

### PR DESCRIPTION
**Pull request by Darkren**
Fixes #435 . 

Implementation follows the same pattern as in the DMSG transport. Also added `sync.Once` to prevent duplicate `close` calls on channels if the `SSHChannel`'s `Close` gets called more than once accindetally.

### CODE REVIEW

File: internal/therealssh/channel.go [hunk 1]
```diff
@@ -35,12 +36,18 @@ type SSHChannel struct {
...
 	dataCh   chan []byte
+
+	doneOnce sync.Once
+	done     chan struct{}
 }
 
 // OpenChannel constructs new SSHChannel with empty Session.
 func OpenChannel(remoteID uint32, remoteAddr *app.Addr, conn net.Conn) *SSHChannel {
-	return &SSHChannel{RemoteID: remoteID, conn: conn, RemoteAddr: remoteAddr, msgCh: make(chan []byte), dataCh: make(chan []byte)}
+	return &SSHChannel{RemoteID: remoteID, conn: conn, RemoteAddr: remoteAddr, msgCh: make(chan []byte),
```
Comment (nkryuchkov) [inline internal/therealssh/channel.go:49]: I think that writing every struct field on a new line might be more readable. What are your thoughts about it?

Comment (evanlinjin) [reply internal/therealssh/channel.go:49]: I think in this case, it is fine. I would leave it as is ☺️

**Review by evanlinjin — APPROVED** [review]
