### PR TITLE
BUG: Ensure modules using internal/httpauth retries with correct nonce after 401. 

### LINKED ISSUE #345: BUG: Ensure modules using internal/httpauth retries with correct nonce after 401.
Log extract:
```
╰─$ go run ./cmd/skywire-node swA.json                                                                                                                                        1 ↵
[2019-05-09T23:46:38+12:00] INFO [pathutil]: using args[0] as config path: swA.json
[2019-05-09T23:46:56+12:00] INFO [messenger]: Opened new channel local ID 3, remote ID 1 with 0348c941c5015a05c455ff238af2e57fb8f914c399aab604e9abb5b32b91a4c1fe
[2019-05-09T23:46:56+12:00] WARN [trmanager]: Failed to accept connection: entry set: status: 401, error: {"error":{"message":"SW-Nonce does not match","code":401}}
```

The client after receiving `{"error":{"message":"SW-Nonce does not match","code":401}}`, must:
1. Grab correct nonce via `(*httpauth.Client).Nonce()`.
2. Retry.

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes #345.

In this PR, `internal/httpauth` requests a new nonce and retries HTTP request if a nonce validation error is returned.

The new behavior may be tested running the following commands:
```
go test ./internal/httpauth -run TestClient_BadNonce
```

### CODE REVIEW

File: internal/httpauth/client.go [hunk 1]
```diff
@@ -86,16 +87,42 @@ func (c *Client) Do(req *http.Request) (*http.Response, error) {
...
+
+		// use nonce, later, if no err from req update such nonce
+		req.Header.Set("SW-Nonce", strconv.FormatUint(uint64(nonce), 10))
+		req.Header.Set("SW-Sig", sign.Hex())
+		req.Header.Set("SW-Public", c.key.Hex())
 
-	res, err := c.client.Do(req)
-	if err != nil {
-		return nil, err
+		res, err = c.client.Do(req)
```
Comment (ayuryshev) [inline internal/httpauth/client.go]: In "theory" recursive calls could continue now infinitely.
IMO it could be be improved with recursion call limit.
With `return nil,err` on overruns.

File: internal/httpauth/client.go [hunk 2]
```diff
@@ -86,16 +87,42 @@ func (c *Client) Do(req *http.Request) (*http.Response, error) {
...
+		}
+
+		nonce, err = c.Nonce(context.Background(), c.key)
+		if err != nil {
+			return nil, err
+		}
+		c.SetNonce(nonce)
+
+		res.Body.Close()
+		time.Sleep(retryInterval)
```
Comment (ayuryshev) [inline internal/httpauth/client.go]: `retryInterval` would be better if it was a settings value IMO

**Review by ayuryshev — CHANGES_REQUESTED** [review]
I think it could be improved with introducing two configuration values:
- timeout between sequential `Client.Do`  requests for nonce
- recursion limit for `Client.Do` requests

File: internal/httpauth/client.go (hunk 1 above)
Comment (ivcosla) [reply internal/httpauth/client.go]: agree

File: internal/httpauth/client.go (hunk 2 above)
Comment (ivcosla) [reply internal/httpauth/client.go]: About this I don't feel it's a parameter that the user is going to be concerned about, I feel it's fine as a constant in package.

**Review by ivcosla — APPROVED** [review]
Good job.

File: internal/httpauth/client.go (hunk 1 above)
Comment (nkryuchkov) [reply internal/httpauth/client.go]: Thanks, I think it's a good idea. Added a commit with the implementation of max retries threshold as well as a test for it.

File: internal/httpauth/client.go (hunk 2 above)
Comment (evanlinjin) [reply internal/httpauth/client.go]: Why do we need a retry parameter? It is not a network error.

File: internal/httpauth/client.go [hunk 3]
```diff
@@ -86,16 +88,46 @@ func (c *Client) Do(req *http.Request) (*http.Response, error) {
...
 		body = auxBody
 	}
-	sign, err := Sign(body, c.getCurrentNonce(), c.sec)
-	if err != nil {
-		return nil, err
-	}
 
-	req.Header.Add("SW-Sig", sign.Hex())
+	var res *http.Response
+	for retriesCount := 0; retriesCount < maxRetries; retriesCount++ {
```
Comment (evanlinjin) [inline internal/httpauth/client.go]: As we are not dealing with a network error, I suggest the following changes:
1. One retry is plenty. If nonce is not synced, we only need to sync once afterwards.
2. We will not need a timeout or `retryInterval`.

Comment (evanlinjin) [reply internal/httpauth/client.go]: Instead of a `for` loop, I would group lines `94-121` into a closure (excluding 110-112). And do `c.Nonce()` + `c.SetNonce()` + `call-closure-again` on error.

File: internal/httpauth/client.go [hunk 4]
```diff
@@ -144,6 +176,26 @@ func (c *Client) incrementNonce() {
 	atomic.AddUint64(&c.nonce, 1)
 }
 
+func (c *Client) isNonceValid(res *http.Response) (bool, error) {
```
Comment (evanlinjin) [inline internal/httpauth/client.go]: 1. Please leave a comment on this function.
2. We aren't using `c *Client`, please have it removed.

File: internal/httpauth/client_test.go [hunk 5]
```diff
@@ -15,34 +17,140 @@ import (
...
 	res.Body.Close()
-	assert.Equal(t, []byte("Hello, client\n"), b)
+	assert.Equal(t, []byte(payload), b)
 	assert.Equal(t, uint64(2), c.nonce)
+
+	headers := <-headerCh
+	checkResp(t, headers, b, pk, 1)
+}
+
+func TestBadNonce(t *testing.T) {
```
Comment (evanlinjin) [inline internal/httpauth/client_test.go]: Please rename to `TestClient_BadNonce` and add a comment summarizing the test.

File: internal/httpauth/client_test.go [hunk 6]
```diff
@@ -15,34 +17,140 @@ import (
...
+	b, err := ioutil.ReadAll(res.Body)
+	require.NoError(t, err)
+	res.Body.Close()
+	assert.Equal(t, uint64(2), c.nonce)
+
+	headers := <-headerCh
+	checkResp(t, headers, b, pk, 1)
+}
+
+func TestTooManyRetries(t *testing.T) {
```
Comment (evanlinjin) [inline internal/httpauth/client_test.go]: Please rename to `TestClient_TooManyRetries` and add a comment summarizing the test.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Good work! Please review my comments.

File: internal/httpauth/client_test.go (hunk 6 above)
Comment (nkryuchkov) [reply internal/httpauth/client_test.go]: Since we do not need to retry multiple times anymore, the test is removed.

**Comment by nkryuchkov** [comment]
@evanlinjin The requested changes are made. Could you review the last changes, please?

File: internal/httpauth/client.go [hunk 7]
```diff
@@ -136,6 +148,21 @@ func (c *Client) SetNonce(n Nonce) {
...
+
+	// use nonce, later, if no err from req update such nonce
+	req.Header.Set("SW-Nonce", strconv.FormatUint(uint64(nonce), 10))
+	req.Header.Set("SW-Sig", sign.Hex())
+	req.Header.Set("SW-Public", c.key.Hex())
+
+	return c.client.Do(req)
+}
+
 func (c *Client) getCurrentNonce() Nonce {
```
Comment (evanlinjin) [inline internal/httpauth/client.go:171]: Operations to `c.nonce` should be atomic. Please use [`atomic.LoadUint64`](https://golang.org/pkg/sync/atomic/#LoadUint64). Also add a comment to line 48, that `c.nonce` is to be handled with the atomic package at all times.

**Review by evanlinjin — CHANGES_REQUESTED** [review]
Looks good. Just one more thing.

**Review by ayuryshev — APPROVED** [review]

File: internal/httpauth/client.go (hunk 7 above)
Comment (nkryuchkov) [reply internal/httpauth/client.go:171]: Fixed

**Review by evanlinjin — APPROVED** [review]
