### PR TITLE
Remove linter excluding rules, clean up code

### LINKED ISSUE #460: Include more errors into lint check
I see that we have `- Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked` in the linter config. 

Although I understand that some of the errors are unlikely to ever happen, I suggest that we remove this or at least include some of its parts and modify the code to be more robust in case of such unexpected scenarios. Such an approach leads to heavy error ignoring all around the code (my concern arised when I took a look at `therealssh` code)

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes #460.

Changes:
- Removed all linter excluding rules
- Removed all `nolint` comments except a couple of them that are really necessary
- Fixed all linter issues after removal
- Made some code cleanup
- Fixed issues found by `gocritic`, `scopelint`, `unconvert` linters

### CODE REVIEW

File: internal/therealproxy/server_test.go [hunk 1]
```diff
@@ -36,7 +35,7 @@ func TestProxy(t *testing.T) {
 	srv, err := NewServer("")
 	require.NoError(t, err)
 
-	l, err := net.Listen("tcp", ":10081") // nolint: gosec
+	l, err := net.Listen("tcp", "localhost:10081")
```
Comment (Darkren) [inline internal/therealproxy/server_test.go]: I'd suggest this to be implemented via `nettest`

File: pkg/httputil/httputil.go [hunk 2]
```diff
@@ -8,15 +8,18 @@ import (
...
+var log = logging.MustGetLogger("httputil")
+
 // WriteJSON writes a json object on a http.ResponseWriter with the given code,
 // panics on marshaling error
 func WriteJSON(w http.ResponseWriter, r *http.Request, code int, v interface{}) {
 	w.Header().Set("Content-Type", "application/json")
 	w.WriteHeader(code)
 	enc := json.NewEncoder(w)
-	if pretty, _ := BoolFromQuery(r, "pretty", false); pretty { //nolint:errcheck
+	if pretty, err := BoolFromQuery(r, "pretty", false); err == nil && pretty {
```
Comment (Darkren) [inline pkg/httputil/httputil.go]: Shouldn't this error be logged?

File: pkg/setup/node_test.go [hunk 3]
```diff
@@ -285,18 +301,23 @@ func (f *muxFactory) Type() string {
 
 type mockNode struct {
 	sync.Mutex
-	rules map[routing.RouteID]routing.Rule
-	tm    *transport.Manager
+	testing *testing.T
```
Comment (Darkren) [inline pkg/setup/node_test.go]: It may ruin tests if we create a single `mockNode` and run several `t.Run` cases against it

**Review by Darkren — CHANGES_REQUESTED** [review]
Overall it's a huge job done and done great, but I left some comments

File: pkg/setup/node_test.go (hunk 3 above)
Comment (nkryuchkov) [reply pkg/setup/node_test.go]: @Darkren well spotted, I'm going to get rid of `testing *testing.T` field

File: pkg/httputil/httputil.go (hunk 2 above)
Comment (nkryuchkov) [reply pkg/httputil/httputil.go]: @Darkren Probably a good idea, thanks. Added some logging.

File: internal/therealproxy/server_test.go (hunk 1 above)
Comment (nkryuchkov) [reply internal/therealproxy/server_test.go]: @Darkren Good idea. Done.

File: cmd/apps/therealproxy-client/therealproxy-client.go [hunk 4]
```diff
@@ -30,7 +30,11 @@ func main() {
 	if err != nil {
 		log.Fatal("Setup failure: ", err)
 	}
-	defer socksApp.Close()
+	defer func() {
+		if err := socksApp.Close(); err != nil {
+			log.Println("Failed to close app: ", err)
```
Comment (evanlinjin) [inline cmd/apps/therealproxy-client/therealproxy-client.go]: No need for space after `app: `. It is `Println` after all.

File: internal/httpauth/client.go [hunk 5]
```diff
@@ -126,10 +133,16 @@ func (c *Client) Nonce(ctx context.Context, key cipher.PubKey) (Nonce, error) {
 	req = req.WithContext(ctx)
 
 	resp, err := c.client.Do(req)
+	if resp != nil {
```
Comment (evanlinjin) [inline internal/httpauth/client.go:136]: Shouldn't we check the `err` first?

File: internal/httpauth/client_test.go [hunk 6]
```diff
@@ -55,8 +54,10 @@ func TestClient(t *testing.T) {
 	require.NoError(t, err)
 
 	b, err := ioutil.ReadAll(res.Body)
+	if b != nil {
```
Comment (evanlinjin) [inline internal/httpauth/client_test.go]: Shouldn't we be checking the error here first?

File: internal/httpauth/client_test.go [hunk 7]
```diff
@@ -83,8 +84,10 @@ func TestClient_BadNonce(t *testing.T) {
...
```
Comment (evanlinjin) [inline internal/httpauth/client_test.go]: Check error first.

File: internal/httpauth/client.go (hunk 5 above)
Comment (nkryuchkov) [reply internal/httpauth/client.go:136]: @evanlinjin Both `resp` and `err` may be non-nil in case of a redirection failure.
Source: http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#close_http_resp_body

File: cmd/apps/therealproxy-client/therealproxy-client.go (hunk 4 above)
Comment (nkryuchkov) [reply cmd/apps/therealproxy-client/therealproxy-client.go]: @evanlinjin Well spotted, thanks.

File: internal/httpauth/client_test.go (hunk 6 above)
Comment (nkryuchkov) [reply internal/httpauth/client_test.go]: @evanlinjin Actually, this looks strange, I'm going to rewrite it.

**Review by evanlinjin — APPROVED** [review]
