### PR TITLE
Read arbitrary hypervisor config from flag instead of args

### LINKED ISSUE #532: Hypervisor cannot read an arbitrary config passed through args
Hypervisor has two `Cobra` commands: 
- root 
- `gen-config`

If using root and specifying a config file to be used, `Cobra` thinks that the config path is a command name, so arbitrary config does not work now. We need to fix this in a way that it reads config from an arbitrary path using a flag.

### PR DESCRIPTION
**Pull request by nkryuchkov**
Closes #532

### CODE REVIEW

File: pkg/util/pathutil/configpath.go [hunk 1]
```diff
@@ -97,8 +97,9 @@ func HypervisorDefaults() ConfigPaths {
 // - From CLI argument.
 // - From ENV.
 // - From a list of default paths.
+// If argsIndex < 0, args search does not take place.
```
Comment (evanlinjin) [inline pkg/util/pathutil/configpath.go]: `args` -> `CLI args` to avoid ambiguity.

**Review by evanlinjin — APPROVED** [review]
Good work. Just the single comment.
