### PR TITLE
Fix messaging system panic #336.

### LINKED ISSUE #336: Messaging system somtimes panics from 'invalid memory address or nil pointer dereference'.
Extracts from logs provided by @ayuryshev 
```
[2019-05-08T13:30:24+03:00] INFO [messenger]: Opened new link with the server 035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282
[2019-05-08T13:30:24+03:00] INFO [messenger]: Updating discovery entry
[2019-05-08T13:30:24+03:00] INFO [messenger]: Opened new channel local ID 0, remote ID 0 with 024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7
[2019-05-08T13:30:24+03:00] WARN [messenger]: Failed to send frame to 035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282: noise handshake: chacha20poly1305: message authentication failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9baf16]

goroutine 133 [running]:
github.com/flynn/noise.(*CipherState).Encrypt(...)
	/home/isk/go/pkg/mod/github.com/flynn/noise@v0.0.0-20180327030543-2492fe189ae6/state.go:33
github.com/skycoin/skywire/internal/noise.(*Noise).EncryptUnsafe(0xc0002126c0, 0xc000482000, 0x208, 0x30a, 0xc00022a618, 0x0, 0xc000084ea0)
	/home/isk/github.com/skycoin/src/skywire/internal/noise/noise.go:126 +0xe6
github.com/skycoin/skywire/pkg/messaging.(*channel).Write.func1(0xc000224990, 0xc000482000, 0x208, 0x30a, 0xc00044d2c0)
	/home/isk/github.com/skycoin/src/skywire/pkg/messaging/channel.go:99 +0xe0
created by github.com/skycoin/skywire/pkg/messaging.(*channel).Write
	/home/isk/github.com/skycoin/src/skywire/pkg/messaging/channel.go:95 +0x17d
```
```
[2019-05-08T13:31:20+03:00] INFO [messenger]: Opened new link with the server 035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282
[2019-05-08T13:31:20+03:00] INFO [messenger]: Updating discovery entry
[2019-05-08T13:31:21+03:00] INFO [messenger]: Opened new channel local ID 0, remote ID 0 with 031b80cd5773143a39d940dc0710b93dcccc262a85108018a7a95ab9af734f8055
[2019-05-08T13:31:21+03:00] WARN [messenger]: Failed to send frame to 035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282: noise handshake: chacha20poly1305: message authentication failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9baf16]

goroutine 208 [running]:
github.com/flynn/noise.(*CipherState).Encrypt(...)
	/home/isk/go/pkg/mod/github.com/flynn/noise@v0.0.0-20180327030543-2492fe189ae6/state.go:33
github.com/skycoin/skywire/internal/noise.(*Noise).EncryptUnsafe(0xc0001d4540, 0xc00011a000, 0x208, 0x2e0, 0xc00022a0c0, 0xc00011c4c0, 0xc000441440)
	/home/isk/github.com/skycoin/src/skywire/internal/noise/noise.go:126 +0xe6
github.com/skycoin/skywire/pkg/messaging.(*channel).Write.func1(0xc0002dc120, 0xc00011a000, 0x208, 0x2e0, 0xc000119800)
	/home/isk/github.com/skycoin/src/skywire/pkg/messaging/channel.go:99 +0xe0
created by github.com/skycoin/skywire/pkg/messaging.(*channel).Write
	/home/isk/github.com/skycoin/src/skywire/pkg/messaging/channel.go:95 +0x17d
```

### PR DESCRIPTION
**Pull request by evanlinjin**
closes #336

### CODE REVIEW

**Comment by evanlinjin** [comment]
Result from following test instructions from: https://github.com/ayuryshev/skywire-services/blob/feature/implement-integration-test-with-restart-cycle-62/integration/README.md#scenario-for-messaging-test-with-unstable-intermediary-skywire-node
image

This appears to be a bug of the chat app.

File: pkg/messaging/channel.go [hunk 1]
```diff
@@ -88,27 +88,28 @@ func (c *channel) Write(p []byte) (n int, err error) {
 		defer cancel()
 	}
 
-	writeChan := make(chan struct {
-		int
-		error
-	})
+	c.wMx.Lock()
+	defer c.wMx.Unlock()
+	data := c.noise.EncryptUnsafe(p)
```
Comment (evanlinjin) [inline pkg/messaging/channel.go:134]: Moved the call to `noise.EncryptUnsafe` out of the go-routine. Hopefully this removes the possibility of calling this after `noise` or `channel` is destroyed.

File: pkg/messaging/channel.go [hunk 2]
```diff
@@ -88,27 +88,28 @@ func (c *channel) Write(p []byte) (n int, err error) {
...
+
+	buf := make([]byte, 2+len(data))
+	binary.BigEndian.PutUint16(buf[:2], uint16(len(data)))
+	copy(buf[2:], data)
+
+	done := make(chan struct{}, 1)
```
Comment (evanlinjin) [inline pkg/messaging/channel.go:140]: Simplified some code while I was at it.

**Comment by ayuryshev** [comment]
[nodeB.log](https://github.com/skycoin/skywire/files/3160074/nodeB.log)

Now it's data race

**Comment by evanlinjin** [comment]
> [nodeB.log](https://github.com/skycoin/skywire/files/3160074/nodeB.log)
> 
> Now it's data race

Thanks, I'll take a deeper dive.

File: pkg/messaging/channel.go [hunk 3]
```diff
@@ -61,6 +59,31 @@ func newChannel(initiator bool, secKey cipher.SecKey, remote cipher.PubKey, link
 	}, nil
 }
 
+// Edges returns the public keys of the channel's edge nodes
+func (c *channel) Edges() [2]cipher.PubKey {
+	return transport.SortPubKeys(c.link.Local(), c.remotePK)
+}
+
+// HandshakeMessage prepares a handshake message safely.
+func (c *channel) HandshakeMessage() ([]byte, error) {
```
Comment (evanlinjin) [inline pkg/messaging/channel.go:86]: To make noise handshake process thread-safe.

File: pkg/messaging/channel.go [hunk 4]
```diff
@@ -20,21 +22,16 @@ type channel struct {
 	buf      *bytes.Buffer
 
 	deadline time.Time
-	closed   bool
+	closed   unsafe.Pointer // unsafe.Pointer is used alongside 'atomic' module for fast, thread-safe access.
```
Comment (nkryuchkov) [inline pkg/messaging/channel.go:27]: I think we should try to avoid using the `unsafe` package. What if we either use `atomic.Value` data type or `(u)int32` here? I would use `uint32` as a boolean considering `0` as `false` and any non-`0` value as `true`.

**Comment by ivcosla** [comment]
I have checked it out, it fixes #346, however, one difference with #344 is that this PR also shows the following message `[2019-05-10T09:40:53+02:00] INFO [trmanager]: Failed to re-dial Transport 236e33a2-8bc1-5b1d-b168-593931d16111: read: chacha20poly1305: message authentication failed
` additionally to `[2019-05-10T09:40:56+02:00] WARN [trmanager]: Failed to re-establish transport: read: chacha20poly1305: message authentication failed` present on #344.


[nodeB.log](https://github.com/skycoin/skywire/files/3165429/nodeB.log)

**Comment by atang152** [comment]
Hi. I also tested this branch. Confirmed that there is no race conditions. Found only the following: WARN [messenger]: Failed to send frame to 035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282: noise handshake: chacha20poly1305: message authentication failed and WARN [trmanager]: Failed to re-establish transport: read: chacha20poly1305: message authentication failed... 

cha_cha_error

[nodeB.log](https://github.com/skycoin/skywire/files/3165452/nodeB.log)

**Review by ayuryshev — APPROVED** [review]
The tests shows that: 
- messaging does not hangs and work correctly with unstable intermediary node
- warning for chacha encryption error on shutdown
- warning for chacha encryption error on startup-reconnect transports

Both warnings could be considered as "non-errors"

Good work!

File: pkg/messaging/channel.go (hunk 4 above)
Comment (evanlinjin) [reply pkg/messaging/channel.go:27]: I've referenced this in a separate ticket.

**Review by ivcosla — APPROVED** [review]
